from flask import Flask, render_template, request, jsonify, send_file
from groq import Groq
from dotenv import load_dotenv
import os
import json
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from io import BytesIO

load_dotenv()

app = Flask(__name__)
client = Groq(api_key=os.environ.get("GROQ_API_KEY"))

GMAIL_USER = os.environ.get("GMAIL_USER")
GMAIL_APP_PASSWORD = os.environ.get("GMAIL_APP_PASSWORD")

@app.route('/')
def index():
    return render_template('index.html')

@app.route('/analyze', methods=['POST'])
def analyze():
    data = request.json
    meeting_notes = data.get('notes', '')
    meeting_title = data.get('title', 'Team Meeting')

    if not meeting_notes:
        return jsonify({'error': 'No meeting notes provided'}), 400

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {
                "role": "system",
                "content": "You are an expert meeting analyzer. Always respond with valid JSON only, no extra text."
            },
            {
                "role": "user",
                "content": f"""Analyze these meeting notes and extract:
1. Action items with person responsible
2. Decisions made
3. Unresolved issues
4. A professional follow up email draft for each person

Meeting Title: {meeting_title}
Meeting Notes:
{meeting_notes}

Respond in this exact JSON format:
{{
    "action_items": [{{"person": "name", "task": "task description", "deadline": "deadline if mentioned or empty string"}}],
    "decisions": ["decision 1", "decision 2"],
    "unresolved": ["issue 1", "issue 2"],
    "emails": [{{"person": "name", "email": "recipient@example.com", "subject": "email subject", "email_draft": "email content"}}],
    "summary": "2 sentence summary of the meeting"
}}"""
            }
        ],
        temperature=0.3,
        max_tokens=1500
    )

    result = json.loads(response.choices[0].message.content)
    return jsonify(result)

@app.route('/send_email', methods=['POST'])
def send_email():
    data = request.json
    recipient = data.get('email')
    subject = data.get('subject')
    body = data.get('body')

    if not recipient or not subject or not body:
        return jsonify({'error': 'Missing email details'}), 400

    try:
        msg = MIMEMultipart()
        msg['From'] = GMAIL_USER
        msg['To'] = recipient
        msg['Subject'] = subject

        msg.attach(MIMEText(body, 'plain'))

        server = smtplib.SMTP('smtp.gmail.com', 587)
        server.starttls()
        server.login(GMAIL_USER, GMAIL_APP_PASSWORD)
        server.sendmail(GMAIL_USER, recipient, msg.as_string())
        server.quit()

        return jsonify({'success': True, 'message': f'Email sent to {recipient}'})

    except Exception as e:
        print(f"EMAIL ERROR: {str(e)}")
        return jsonify({'error': str(e)}), 500

@app.route('/export_pdf', methods=['POST'])
def export_pdf():
    data = request.json
    title = data.get('title', 'Meeting Report')
    summary = data.get('summary', '')
    action_items = data.get('action_items', [])
    decisions = data.get('decisions', [])
    unresolved = data.get('unresolved', [])
    emails = data.get('emails', [])

    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter,
                           rightMargin=inch, leftMargin=inch,
                           topMargin=inch, bottomMargin=inch)

    styles = getSampleStyleSheet()
    story = []

    # Title
    title_style = ParagraphStyle('CustomTitle', parent=styles['Title'],
                                  fontSize=24, textColor=colors.HexColor('#0078d4'),
                                  spaceAfter=12)
    story.append(Paragraph(f"{title}", title_style))
    story.append(Paragraph("Generated by MeetAgent AI", styles['Normal']))
    story.append(Spacer(1, 20))

    # Summary
    if summary:
        story.append(Paragraph("Meeting Summary", styles['Heading2']))
        story.append(Paragraph(summary, styles['Normal']))
        story.append(Spacer(1, 12))

    # Action Items
    story.append(Paragraph("Action Items", styles['Heading2']))
    if action_items:
        table_data = [['Person', 'Task', 'Deadline']]
        for item in action_items:
            table_data.append([
                item.get('person', ''),
                item.get('task', ''),
                item.get('deadline', 'Not specified')
            ])
        table = Table(table_data, colWidths=[1.5*inch, 3.5*inch, 1.5*inch])
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#0078d4')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 12),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.HexColor('#f0f7ff'), colors.white]),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#e0e0e0')),
            ('PADDING', (0, 0), (-1, -1), 8),
        ]))
        story.append(table)
    story.append(Spacer(1, 16))

    # Decisions
    story.append(Paragraph("Decisions Made", styles['Heading2']))
    for d in decisions:
        story.append(Paragraph(f"• {d}", styles['Normal']))
    story.append(Spacer(1, 16))

    # Unresolved
    story.append(Paragraph("Unresolved Issues", styles['Heading2']))
    for u in unresolved:
        story.append(Paragraph(f"• {u}", styles['Normal']))
    story.append(Spacer(1, 16))

    # Emails
    story.append(Paragraph("Generated Emails", styles['Heading2']))
    for email in emails:
        story.append(Paragraph(f"To: {email.get('person', '')}", styles['Heading3']))
        story.append(Paragraph(f"Subject: {email.get('subject', '')}", styles['Normal']))
        story.append(Paragraph(email.get('email_draft', ''), styles['Normal']))
        story.append(Spacer(1, 12))

    doc.build(story)
    buffer.seek(0)

    return send_file(buffer, as_attachment=True,
                    download_name=f"{title.replace(' ', '_')}_MeetAgent.pdf",
                    mimetype='application/pdf')

if __name__ == '__main__':
    port = int(os.environ.get('PORT', 5000))
    app.run(host='0.0.0.0', port=port, debug=False)
